import type { Config } from 'tailwindcss';

/** All visual values come from CSS variables in src/styles/tokens.css (UX-10). Re-skin there, not here. */
const tokenColor = (name: string) => `rgb(var(--${name}) / <alpha-value>)`;

const config: Config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: tokenColor('background'),
        canvas: tokenColor('canvas'),
        surface: tokenColor('surface'),
        'surface-muted': tokenColor('surface-muted'),
        'surface-container': tokenColor('surface-container'),
        'surface-container-high': tokenColor('surface-container-high'),
        'surface-subtle': tokenColor('surface-subtle'),
        dropzone: tokenColor('dropzone'),
        border: tokenColor('border'),
        outline: tokenColor('outline'),
        'outline-variant': tokenColor('outline-variant'),
        text: tokenColor('text'),
        'text-muted': tokenColor('text-muted'),
        placeholder: tokenColor('placeholder'),
        primary: tokenColor('primary'),
        'primary-foreground': tokenColor('primary-foreground'),
        'primary-container': tokenColor('primary-container'),
        'primary-soft': tokenColor('primary-soft'),
        accent: tokenColor('accent'),
        success: tokenColor('success'),
        'success-foreground': tokenColor('success-foreground'),
        'success-accent': tokenColor('success-accent'),
        'success-soft': tokenColor('success-soft'),
        warning: tokenColor('warning'),
        'warning-foreground': tokenColor('warning-foreground'),
        'warning-accent': tokenColor('warning-accent'),
        'warning-soft': tokenColor('warning-soft'),
        draft: tokenColor('draft'),
        'draft-foreground': tokenColor('draft-foreground'),
        danger: tokenColor('danger'),
        'danger-foreground': tokenColor('danger-foreground'),
        'danger-soft': tokenColor('danger-soft'),
        info: tokenColor('info'),
        'info-soft': tokenColor('info-soft'),
        'focus-ring': tokenColor('focus-ring'),
        overlay: tokenColor('overlay'),
        'card-border': 'var(--card-border)',
        'card-border-hover': 'var(--card-border-hover)',
        glass: 'var(--glass)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        glow: 'var(--shadow-glow)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        heading: ['var(--font-heading)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: ['var(--text-xs)', { lineHeight: 'var(--leading-xs)' }],
        sm: ['var(--text-sm)', { lineHeight: 'var(--leading-sm)' }],
        base: ['var(--text-base)', { lineHeight: 'var(--leading-base)' }],
        lg: ['var(--text-lg)', { lineHeight: 'var(--leading-lg)' }],
        xl: ['var(--text-xl)', { lineHeight: 'var(--leading-xl)' }],
        '2xl': ['var(--text-2xl)', { lineHeight: 'var(--leading-2xl)' }],
        '3xl': ['var(--text-3xl)', { lineHeight: 'var(--leading-3xl)' }],
        '4xl': ['var(--text-4xl)', { lineHeight: 'var(--leading-4xl)', letterSpacing: '-0.02em' }],
        'hero-mobile': [
          'var(--text-hero-mobile)',
          { lineHeight: 'var(--leading-hero-mobile)', letterSpacing: '-0.02em' },
        ],
        'label-lg': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '600' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', fontWeight: '600', letterSpacing: '0.02em' }],
        'label-sm': [
          '0.625rem',
          { lineHeight: '0.875rem', fontWeight: '600', letterSpacing: '0.04em' },
        ],
      },
      spacing: {
        'page-x': 'var(--space-page-x)',
        'page-y': 'var(--space-page-y)',
        gutter: 'var(--space-gutter)',
        sidebar: 'var(--size-sidebar)',
        header: 'var(--size-header)',
        'bottom-nav': 'var(--size-bottom-nav)',
        tree: 'var(--size-tree)',
        inspector: 'var(--size-inspector)',
      },
      maxWidth: {
        content: 'var(--size-content)',
        prose: 'var(--size-prose)',
        canvas: 'var(--size-canvas)',
      },
      transitionDuration: {
        fast: 'var(--motion-fast)',
        base: 'var(--motion-base)',
      },
      transitionTimingFunction: {
        bounce: 'var(--ease-bounce)',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-up': {
          from: { transform: 'translateY(8px)', opacity: '0' },
          to: { transform: 'none', opacity: '1' },
        },
        'slide-in-right': { from: { transform: 'translateX(100%)' }, to: { transform: 'none' } },
        shimmer: {
          '0%': { opacity: '0.55' },
          '50%': { opacity: '1' },
          '100%': { opacity: '0.55' },
        },
      },
      animation: {
        'fade-in': 'fade-in var(--motion-base) ease-out',
        'slide-up': 'slide-up var(--motion-base) ease-out',
        'slide-in-right': 'slide-in-right var(--motion-base) ease-out',
        shimmer: 'shimmer 1.4s ease-in-out infinite',
        'pop-in': 'pop-in var(--motion-base) var(--ease-bounce)',
      },
    },
  },
  plugins: [],
};

export default config;
